apiVersion: v1
kind: Service
metadata:
  labels:
    app: suber
  name: suber
  namespace: b6000530
spec:
  clusterIP: 10.108.173.187
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: suber
  sessionAffinity: None
  type: ClusterIP
